//CD Pipeline

pipeline{
  agent any
  
  parameters {
        string(name: 'FRONTEND_IMAGE_TAG', defaultValue: '', description: 'Frontend Docker tag of the image built by the CI job')
        string(name: 'BACKEND_IMAGE_TAG', defaultValue: '', description: 'Backend Docker tag of the image built by the CI job')
    }
  
  stages{
   stage('Git: Code Checkout') {
       steps {
                script{
                   git url:"https://github.com/DevMadhup/Wanderlust-Mega-Project.git", branch:"main"
                }
            }
        }
        
    stage('Verify: Docker Image Tags') {
            steps {
                script{
                    echo "FRONTEND_IMAGE_TAG: ${params.FRONTEND_IMAGE_TAG}"
                    echo "BACKEND_IMAGE_TAG: ${params.BACKEND_IMAGE_TAG}"
                }
            }
        }
    
    stage("Update: Kubernetes manifests"){
            steps{
              //finds wanderlust-backend-beta.* in backend.yaml file and replaces everything(*) after it with ${params.BACKEND_IMAGE_TAG} and same for frontend
                script{
                    dir('kubernetes'){
                        sh """
                            sed -i -e s/wanderlust-backend-beta.*/wanderlust-backend-beta:${params.BACKEND_IMAGE_TAG}/g backend.yaml
                        """
                    }
                    
                    dir('kubernetes'){
                        sh """
                            sed -i -e s/wanderlust-frontend-beta.*/wanderlust-frontend-beta:${params.FRONTEND_IMAGE_TAG}/g frontend.yaml
                        """
                    }
                    
                }
            }
        }
  stage("Update changes and push on Github"){
            steps{
                script{
                    withCredentials([gitUsernamePassword(credentialsId: 'Github-cred', gitToolName: 'Default')]) {
                        sh """
                        echo "Checking repository status: "
                        git status
                    
                        echo "Adding changes to git: "
                        git add .
                        
                        echo "Commiting changes: "
                        git commit -m "Updated environment variables"
                        
                        echo "Pushing changes to github: "
                        git push https://github.com/DevMadhup/Wanderlust-Mega-Project.git main
                    """
                    }
                }
            }
     }
  }
    
 post {
        success {
            script {
                emailext attachLog: true,
                from: 'zahramurtaza28@gmail.com',
                subject: "Wanderlust Application has been updated and deployed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                        <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">URL: ${env.BUILD_URL}</p>
                        </div>
                    </body>
                    </html>
            """,
            to: 'zahramurtaza28@gmail.com',
            mimeType: 'text/html'
            }
        }
      failure {
            script {
                emailext attachLog: true,
                from: 'zahramurtaza28@gmail.com',
                subject: "Wanderlust Application build failed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                    </body>
                    </html>
            """,
            to: 'zahramurtaza28@gmail.com',
            mimeType: 'text/html'
            }
        }
  
  }
}
